baseURL = ""
title = "Albertcacv | Blog"

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
author = "AlbertcacV"
description = "Ciberseguridad y Desarrollo Web, todo en uno!"
favicon = "/images/favicon.jpg"
github = "albertcacv"
keywords = "blog, google analytics"
lastmod = true
linkedin = "albertcacv"
location = "Spain"
twitter = "albertcacv"
url = "https://albertcacv.dev"
userStatusEmoji = "âœ…"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]
